variables:
  KUBE_NAMESPACE:                  "processbot"
  CI_REGISTRY:                     "paritytech"
  GIT_STRATEGY:                    fetch
  GIT_DEPTH:                       3
  CARGO_TARGET_DIR:                "/ci-cache/${CI_PROJECT_NAME}/targets/${CI_COMMIT_REF_NAME}/${CI_JOB_NAME}"
  VAULT_SERVER_URL:                "https://vault.parity-mgmt-vault.parity.io"
  VAULT_AUTH_PATH:                 "gitlab-parity-io-jwt"
  VAULT_AUTH_ROLE:                 "cicd_gitlab_parity_${CI_PROJECT_NAME}"
  GITHUB_ORGANIZATION:             "paritytech"

default:
  image: paritytech/ci-linux:production
  retry:
    max: 2
    when:
      - runner_system_failure
      - unknown_failure
      - api_failure
  tags:
    - linux-docker

stages:
  - pre
  - check
  - test
  - build
  - dockerize
  - deploy

#### stage: pre
.uninstall-deployment: &uninstall-deployment
  image: paritytech/kubetools:3.5.3
  tags:
    - kubernetes-parity-build
  stage: pre
  interruptible: true
  script:
    - helm uninstall "$KUBE_NAMESPACE" --namespace "$KUBE_NAMESPACE"

uninstall-staging:
  <<: *uninstall-deployment
  environment:
    name: staging

#### stage:                        deploy

.deploy-k8s:                       &deploy-k8s
  image:                           paritytech/kubetools:3.5.3
  interruptible:                   true
  secrets:
    PROCESSBOT_KEY:
      vault:                       cicd/gitlab/$CI_PROJECT_PATH/$CI_ENVIRONMENT_NAME/PROCESSBOT_KEY@kv
      file:                        false
    GITHUB_APP_ID:
      vault:                       cicd/gitlab/$CI_PROJECT_PATH/$CI_ENVIRONMENT_NAME/GITHUB_APP_ID@kv
      file:                        false
    WEBHOOK_SECRET:
      vault:                       cicd/gitlab/$CI_PROJECT_PATH/$CI_ENVIRONMENT_NAME/WEBHOOK_SECRET@kv
      file:                        false
  # PROCESSBOT_KEY should be base64 encoded
  script:
    - helm upgrade processbot ./helm
      --install
      --namespace "${KUBE_NAMESPACE}"
      --values "helm/values-${CI_ENVIRONMENT_NAME}.yaml"
      --set "app.INSTALLATION_LOGIN=${GITHUB_ORGANIZATION}"
      --set "app.KUBE_NAMESPACE=${KUBE_NAMESPACE}"
      --set "app.DOCKER_TAG=pre-v0.16"
      --set "app.PROCESSBOT_KEY=${PROCESSBOT_KEY}"
      --set "app.GITHUB_APP_ID=${GITHUB_APP_ID}"
      --set "app.WEBHOOK_SECRET=${WEBHOOK_SECRET}"
      --set "app.TEAM_LEADS_TEAM=${TEAM_LEADS_TEAM}"
      --set "app.CORE_DEVS_TEAM=${CORE_DEVS_TEAM}"

deploy-staging:
  stage:                           deploy
  <<:                              *deploy-k8s
  environment:
    name: staging
  tags:
    - kubernetes-parity-build
