orgName: paritytech
dockerTag: from-gitlab-vars
processbot:
  config:
    KUBE_NAMESPACE: processbot
    WEBHOOK_PORT: 8080
    BURNIN_GITLAB_HOST: from-gitlab-vars
    BURNIN_GITLAB_PROJECT: from-gitlab-vars
  secret:
    PROCESSBOT_KEY: from-gitlab-vars
    BAMBOO_TOKEN: from-gitlab-vars
    MATRIX_ACCESS_TOKEN: from-gitlab-vars
    WEBHOOK_SECRET: from-gitlab-vars
    BURNIN_GITLAB_TOKEN: from-gitlab-vars
