environment: production
ingress:
  domain: processbot.parity.io
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.entryPoints: "https,http"
processbot:
  config:
    GITHUB_APP_ID: 51719
    GITLAB_PROJECT: parity/polkadot
