---
# Ingress for the webhook
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: processbot-ingress
  namespace: {{ .Values.processbot.config.KUBE_NAMESPACE }}
  labels:
    app: parity-processbot
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.ingress.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: parity-processbot
          servicePort: {{ .Values.processbot.config.WEBHOOK_PORT }}
  tls:
  - hosts:
    - {{ .Values.ingress.domain }}
    secretName: {{ .Values.ingress.domain }}
