---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: processbot-ingress
  namespace: {{ .Values.processbot.config.KUBE_NAMESPACE }}
  labels:
    app: parity-processbot
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http01
    external-dns.alpha.kubernetes.io/target: traefik-external.parity-stg.parity.io.
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
  - host: {{ .Values.ingressDomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: parity-processbot
          servicePort: {{ .Values.processbot.config.WEBHOOK_PORT }}
  tls:
  - hosts:
    - {{ .Values.ingressDomain }}
    secretName: {{ .Values.ingressDomain }}
